"""
Render the checkpoint 3D Bengaluru Ecological Stresspeaks terrain.

Input assets are generated by scripts/18_build_ecological_stress_samples.py:
- outputs/stresspeaks/ecological_stress_mesh_balanced.obj
- outputs/stresspeaks/ecological_stress_drape.json

This render deliberately avoids the previous heat-only blob style. The city outline
comes from the mesh itself, with steep boundary sides, subdued stress bands, a light
reference-style grid, and small top-risk ward outlines only.
"""
from __future__ import annotations

import json
import math
from pathlib import Path

import bpy
from mathutils import Vector


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "outputs" / "stresspeaks"
MESH_OBJ = OUT / "ecological_stress_mesh_balanced.obj"
DRAPE_JSON = OUT / "ecological_stress_drape.json"
RAW_RENDER = OUT / "sample_ecological_stresspeaks_render_raw.png"
BLEND_FILE = OUT / "ecological_stresspeaks_checkpoint.blend"

Z_SCALE = 0.32
LINE_Z_OFFSET = 0.012
DRAW_BOUNDARY_OVERLAY = False
BG = (0.925, 0.912, 0.875, 1.0)
GRID = (0.72, 0.70, 0.66, 1.0)
INK = (0.115, 0.098, 0.082, 1.0)
OUTLINE = (0.22, 0.18, 0.14, 1.0)
WARD_TRACE = (0.92, 0.80, 0.62, 1.0)

# Palette B from the revised direction, expanded into restrained contour bands.
STRESS_BANDS = [
    "#dfe8df",
    "#d7ddcd",
    "#d9ca96",
    "#cfaa69",
    "#bf6f43",
    "#a9513a",
    "#7c2830",
    "#4f2022",
    "#2b1718",
]


def hex_to_rgba(value: str, alpha: float = 1.0) -> tuple[float, float, float, float]:
    value = value.lstrip("#")
    return (
        int(value[0:2], 16) / 255,
        int(value[2:4], 16) / 255,
        int(value[4:6], 16) / 255,
        alpha,
    )


def reset_scene() -> None:
    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.object.delete()


def make_mat(name: str, color: tuple[float, float, float, float], roughness: float = 0.86) -> bpy.types.Material:
    mat = bpy.data.materials.new(name)
    mat.diffuse_color = color
    mat.use_nodes = True
    bsdf = mat.node_tree.nodes.get("Principled BSDF")
    if bsdf:
        if "Base Color" in bsdf.inputs:
            bsdf.inputs["Base Color"].default_value = color
        if "Roughness" in bsdf.inputs:
            bsdf.inputs["Roughness"].default_value = roughness
        if "Metallic" in bsdf.inputs:
            bsdf.inputs["Metallic"].default_value = 0.0
        if "Alpha" in bsdf.inputs:
            bsdf.inputs["Alpha"].default_value = color[3]
    if color[3] < 1.0:
        mat.blend_method = "BLEND"
        mat.use_screen_refraction = False
    return mat


def smooth_top_vertices(
    verts: list[tuple[float, float, float]],
    faces: list[tuple[int, ...]],
    iterations: int = 14,
    factor: float = 0.48,
) -> list[tuple[float, float, float]]:
    z_values = [vert[2] for vert in verts]
    neighbors: list[set[int]] = [set() for _ in verts]
    for face in faces:
        if not face or any(z_values[idx] <= 1e-6 for idx in face):
            continue
        for pos, idx in enumerate(face):
            prev_idx = face[pos - 1]
            next_idx = face[(pos + 1) % len(face)]
            neighbors[idx].add(prev_idx)
            neighbors[idx].add(next_idx)

    active = [idx for idx, linked in enumerate(neighbors) if linked and z_values[idx] > 1e-6]
    for _ in range(iterations):
        next_z = z_values[:]
        for idx in active:
            avg = sum(z_values[n] for n in neighbors[idx]) / len(neighbors[idx])
            next_z[idx] = z_values[idx] * (1.0 - factor) + avg * factor
        z_values = next_z
    return [(x, y, z_values[idx]) for idx, (x, y, _z) in enumerate(verts)]


def import_terrain() -> bpy.types.Object:
    if not MESH_OBJ.exists():
        raise FileNotFoundError(MESH_OBJ)

    verts: list[tuple[float, float, float]] = []
    faces: list[tuple[int, ...]] = []
    with MESH_OBJ.open("r", encoding="utf-8") as handle:
        for line in handle:
            if line.startswith("v "):
                _tag, x, y, z = line.split()
                verts.append((float(x), float(y), float(z)))
            elif line.startswith("f "):
                parts = [item.split("/")[0] for item in line.split()[1:]]
                faces.append(tuple(int(item) - 1 for item in parts))

    verts = smooth_top_vertices(verts, faces)
    mesh = bpy.data.meshes.new("stresspeaks_mesh")
    mesh.from_pydata(verts, [], faces)
    mesh.update()
    terrain = bpy.data.objects.new("Bengaluru ecological stress terrain", mesh)
    bpy.context.collection.objects.link(terrain)
    terrain.name = "Bengaluru ecological stress terrain"
    terrain.data.name = "stresspeaks_mesh"

    for vert in terrain.data.vertices:
        vert.co.z *= Z_SCALE

    z_values = [vert.co.z for vert in terrain.data.vertices]
    z_min, z_max = min(z_values), max(z_values)
    z_span = max(z_max - z_min, 1e-6)

    band_mats = [
        make_mat(f"stress band {idx + 1}", hex_to_rgba(color), 0.9)
        for idx, color in enumerate(STRESS_BANDS)
    ]
    for mat in band_mats:
        terrain.data.materials.append(mat)

    for poly in terrain.data.polygons:
        avg_z = sum(terrain.data.vertices[i].co.z for i in poly.vertices) / len(poly.vertices)
        norm = max(0.0, min(1.0, (avg_z - z_min) / z_span))
        idx = min(len(band_mats) - 1, int(norm * len(band_mats)))
        poly.material_index = idx
        poly.use_smooth = True

    modifier = terrain.modifiers.new("weighted cliff normals", "WEIGHTED_NORMAL")
    modifier.weight = 45
    modifier.keep_sharp = True
    return terrain


def make_curve(
    name: str,
    polylines: list[list[list[float]]],
    mat: bpy.types.Material,
    bevel_depth: float,
    z_offset: float,
) -> bpy.types.Object:
    curve = bpy.data.curves.new(name, "CURVE")
    curve.dimensions = "3D"
    curve.resolution_u = 1
    curve.bevel_depth = bevel_depth
    curve.bevel_resolution = 2
    for line in polylines:
        if len(line) < 2:
            continue
        spline = curve.splines.new("POLY")
        spline.points.add(len(line) - 1)
        for point, coords in zip(spline.points, line):
            point.co = (coords[0], coords[1], coords[2] * Z_SCALE + z_offset, 1.0)
    obj = bpy.data.objects.new(name, curve)
    bpy.context.collection.objects.link(obj)
    obj.data.materials.append(mat)
    return obj


def add_grid() -> None:
    grid_mat = make_mat("subtle diagonal grid", GRID, 0.95)
    size = 5.4
    spacing = 0.18
    z = -0.028
    curve = bpy.data.curves.new("reference grid", "CURVE")
    curve.dimensions = "3D"
    curve.resolution_u = 1
    curve.bevel_depth = 0.0012
    curve.bevel_resolution = 0
    count = int((size * 2) / spacing) + 1
    for family_angle in (math.radians(32), math.radians(122)):
        direction = Vector((math.cos(family_angle), math.sin(family_angle), 0.0))
        normal = Vector((-direction.y, direction.x, 0.0))
        for idx in range(count):
            offset = -size + idx * spacing
            center = normal * offset
            a = center - direction * size
            b = center + direction * size
            spline = curve.splines.new("POLY")
            spline.points.add(1)
            spline.points[0].co = (a.x, a.y, z, 1.0)
            spline.points[1].co = (b.x, b.y, z, 1.0)
    obj = bpy.data.objects.new("subtle diagonal grid", curve)
    bpy.context.collection.objects.link(obj)
    obj.data.materials.append(grid_mat)


def add_base_plane() -> None:
    mat = make_mat("warm off-white ground", BG, 0.88)
    bpy.ops.mesh.primitive_plane_add(size=8.0, location=(0, 0, -0.032))
    plane = bpy.context.object
    plane.name = "off-white base plane"
    plane.data.materials.append(mat)


def add_lighting() -> None:
    bpy.ops.object.light_add(type="AREA", location=(-2.2, -2.4, 4.2))
    key = bpy.context.object
    key.name = "large softbox key light"
    key.data.energy = 520
    key.data.size = 4.8

    bpy.ops.object.light_add(type="AREA", location=(2.2, 2.0, 2.6))
    fill = bpy.context.object
    fill.name = "low fill light"
    fill.data.energy = 65
    fill.data.size = 5.4


def look_at(obj: bpy.types.Object, target: tuple[float, float, float]) -> None:
    direction = Vector(target) - obj.location
    obj.rotation_euler = direction.to_track_quat("-Z", "Y").to_euler()


def setup_camera() -> None:
    bpy.ops.object.camera_add(location=(0.0, -3.65, 5.35))
    camera = bpy.context.object
    look_at(camera, (0.0, -0.01, 0.08))
    camera.data.type = "ORTHO"
    camera.data.ortho_scale = 3.55
    camera.data.lens = 70
    bpy.context.scene.camera = camera


def setup_render() -> None:
    scene = bpy.context.scene
    try:
        scene.render.engine = "BLENDER_EEVEE_NEXT"
    except TypeError:
        scene.render.engine = "BLENDER_EEVEE"
    if hasattr(scene, "eevee"):
        if hasattr(scene.eevee, "taa_render_samples"):
            scene.eevee.taa_render_samples = 96
        if hasattr(scene.eevee, "use_gtao"):
            scene.eevee.use_gtao = True
        if hasattr(scene.eevee, "gtao_distance"):
            scene.eevee.gtao_distance = 2.5
        if hasattr(scene.eevee, "gtao_factor"):
            scene.eevee.gtao_factor = 1.35
    scene.render.resolution_x = 1800
    scene.render.resolution_y = 2700
    scene.render.film_transparent = False
    scene.world = bpy.data.worlds.new("warm paper world")
    scene.world.color = BG[:3]
    scene.view_settings.view_transform = "Filmic"
    scene.view_settings.look = "Medium High Contrast"
    scene.view_settings.exposure = -0.05
    scene.view_settings.gamma = 1.0
    scene.render.image_settings.file_format = "PNG"
    scene.render.filepath = str(RAW_RENDER)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    reset_scene()
    setup_render()
    add_base_plane()
    add_grid()
    terrain = import_terrain()

    drape = json.loads(DRAPE_JSON.read_text(encoding="utf-8"))
    if DRAW_BOUNDARY_OVERLAY:
        outline_mat = make_mat("thin city outline", OUTLINE, 0.82)
        make_curve("Bengaluru outer boundary", drape.get("outline_polylines", []), outline_mat, 0.0046, LINE_Z_OFFSET)

    bpy.context.view_layer.objects.active = terrain
    terrain.select_set(True)
    add_lighting()
    setup_camera()

    bpy.ops.wm.save_as_mainfile(filepath=str(BLEND_FILE))
    bpy.ops.render.render(write_still=True)


if __name__ == "__main__":
    main()
